### ISSUE TITLE
rapidsms.org SSL certificate expired

### ISSUE THREAD

**Issue by BobWhitelock** [rapidsms/rapidsms.org#161]
When visiting rapidsms.org my browser is redirected to use https, however the SSL certificate has expired so I then get a security warning; it says it expired on 26th August 2015.

**Comment by vkurup** [comment]
Thanks for the heads-up! We're in the process of renewing.

**Comment by vkurup** [comment]
Renewed with a calendar entry made for next year. Thanks again for the notification!
